
CREATE DATABASE reserva_sala;

USE sistema_reserva_sala;

CREATE TABLE SALA (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nomeSala VARCHAR(45) NOT NULL,
  andar VARCHAR(25) NOT NULL,
  capacidadeINT(10) NOT NULL,
  tipo TEXT NOT NULL
);


CREATE TABLE AREA (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nomeArea VARCHAR(100) NOT NULL
);

CREATE TABLE SUBAREA (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nomeSubarea VARCHAR(30) NOT NULL,
  corArea VARCHAR(20) NOT NULL,
  idArea INT NOT NULL,
  FOREIGN KEY (idArea) REFERENCES AREA(id)
);

CREATE TABLE CURSO (
  ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
  nome_curso VARCHAR(45) NOT NULL,
  siglaCurso VARCHAR(10) NOT NULL,
);

-- Criar tabela DOCENTE
CREATE TABLE DOCENTE (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nomeDocente VARCHAR(30) NOT NULL
);

-- Criar tabela TURMA
CREATE TABLE TURMA (
  id INT PRIMARY KEY AUTO_INCREMENT,
  idCurso INT NOT NULL,
  idDocente INT NOT NULL,
  codigoTurma VARCHAR(30) NOT NULL,
  FOREIGN KEY (idCurso) REFERENCES CURSO(id),
  FOREIGN KEY (idDocente) REFERENCES DOCENTE(id)
);

-- Criar tabela RESERVA
CREATE TABLE RESERVA (
  id INT PRIMARY KEY AUTO_INCREMENT,
  idSala INT NOT NULL,
  idTurma INT NOT NULL,
  dataInicio DATETIME NOT NULL,
  dataFim DATETIME NOT NULL default current_timestamp on UPDATE current_timestamp,
  horaInicio TIME NOT NULL,
  horaFim TIME NOT NULL,
  FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA),
  FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
);
